### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by zvezdochiot** [ZQPei/patchmatch_inpainting#4]
Maybe https://github.com/ImageProcessing-ElectronicPublications/gimp-plugin-colors-bimod/blob/master/LICENSE ?

PS: Just asked

**Comment by ZQPei** [comment]
How about you make a pull request?

**Comment by zvezdochiot** [comment]
First need to know the preferences. Is there a need for PR? Detail breakdown by commits?

**Comment by ZQPei** [comment]
In fact this code has a hidden bug. If process one image at a time, it is fine.
However, if you change the main function to process hundreds of images in a folder at the same time with a `for` loop, it will run out of memory, which means **there are somewhere that forget to free memory after `alloc`** and this bug is negligible when processing one image.
I tried to find this bug, but failed. That is why I do image inpainting one by one.
How about you have a try to go?

**Comment by zvezdochiot** [comment]
Memory alloc? We will see.

But why not use the "simple" cli? And to work with an array through bash? And the total log is not needed, it is about nothing.
